"""Add Admins table

Revision ID: 09b93e8db926
Revises: b814a0dbba57
Create Date: 2023-03-24 21:55:21.017015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b93e8db926'
down_revision = 'b814a0dbba57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    admins_table = op.create_table('Admins',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    # ### end Alembic commands ###

    # seed with initial (hard-coded) data
    op.bulk_insert(
        admins_table,
        [{'email': 'ectc.headtable@gmail.com', 'is_super_admin': True}],
    )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Admins')
    # ### end Alembic commands ###
