"""Add Mailchimp template folder id to GlobalState

Revision ID: 1af899caec39
Revises: c99c323b34f5
Create Date: 2023-03-30 14:12:46.741693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1af899caec39'
down_revision = 'c99c323b34f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailchimp_folder_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('mailchimp_folder_id')

    # ### end Alembic commands ###
