"""Add Mailchimp audience id to GlobalState

Revision ID: 28dac2fed2fc
Revises: 8631531248fe
Create Date: 2023-03-18 08:35:32.224759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28dac2fed2fc'
down_revision = '8631531248fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailchimp_audience_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('mailchimp_audience_id')

    # ### end Alembic commands ###
