"""Add last sent Mailchimp template id and subject to GlobalState

Revision ID: 32b526e449c1
Revises: 1af899caec39
Create Date: 2023-04-01 12:14:12.445515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b526e449c1'
down_revision = '1af899caec39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailchimp_template_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('mailchimp_subject', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('mailchimp_template_id')
        batch_op.drop_column('mailchimp_subject')

    # ### end Alembic commands ###
