"""Create BlastEmailsSent table

Revision ID: 3d509fadd773
Revises: f87a755022eb
Create Date: 2023-04-21 00:23:30.263118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d509fadd773'
down_revision = 'f87a755022eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('BlastEmailsSent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('time_sent', sa.DateTime(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BlastEmailsSent')
    # ### end Alembic commands ###
