"""Add tables/columns for sending to subscribers

Revision ID: 41e45d919081
Revises: 02a758ab31db
Create Date: 2023-04-10 17:44:22.945217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41e45d919081'
down_revision = '02a758ab31db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserSubscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'school', 'code', name='_email_school_team_code')
    )
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('send_to_subscribers', sa.Boolean(), nullable=False, server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('send_to_subscribers')

    op.drop_table('UserSubscriptions')
    # ### end Alembic commands ###
