"""Add Mailchimp API key to GlobalState

Revision ID: 6a005fc91e10
Revises: afb620f18f28
Create Date: 2023-03-15 23:41:37.937048

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '6a005fc91e10'
down_revision = 'afb620f18f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailchimp_api_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('mailchimp_api_key')

    # ### end Alembic commands ###
