"""Add Mailchimp audience tag to GlobalState

Revision ID: 6ee3ba2d87cc
Revises: e45715456936
Create Date: 2023-03-28 12:03:32.128906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ee3ba2d87cc'
down_revision = 'e45715456936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mailchimp_audience_tag', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('mailchimp_audience_tag')

    # ### end Alembic commands ###
