"""Add last matches query to GlobalState

Revision ID: 8631531248fe
Revises: 6a005fc91e10
Create Date: 2023-03-16 21:49:13.198487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8631531248fe'
down_revision = '6a005fc91e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_matches_query', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('last_matches_query')

    # ### end Alembic commands ###
