"""Create roster tables: Schools, Users, Teams

Revision ID: afb620f18f28
Revises: 6927bd10e170
Create Date: 2023-03-09 14:46:27.404738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afb620f18f28'
down_revision = '6927bd10e170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['Schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('light_id', sa.Integer(), nullable=True),
    sa.Column('middle_id', sa.Integer(), nullable=True),
    sa.Column('heavy_id', sa.Integer(), nullable=True),
    sa.Column('alternate_ids', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['heavy_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['light_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['middle_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['Schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'code', name='_school_team_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Teams')
    op.drop_table('Users')
    op.drop_table('Schools')
    # ### end Alembic commands ###
