"""Create TMSMatchStatuses and EmailsSent tables

Revision ID: b814a0dbba57
Revises: 28dac2fed2fc
Create Date: 2023-03-19 11:35:01.762990

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b814a0dbba57'
down_revision = '28dac2fed2fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('EmailsSent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_sent', sa.DateTime(), nullable=False),
    sa.Column('matches', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('TMSMatchStatuses',
    sa.Column('match_number', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('match_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TMSMatchStatuses')
    op.drop_table('EmailsSent')
    # ### end Alembic commands ###
