"""Add last roster spreadsheet and fetched time columns to GlobalState

Revision ID: c45d23518e0d
Revises: e18879395263
Create Date: 2023-03-08 16:21:49.384531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c45d23518e0d'
down_revision = 'e18879395263'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_roster_spreadsheet', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_fetched_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('GlobalState', schema=None) as batch_op:
        batch_op.drop_column('last_fetched_time')
        batch_op.drop_column('last_roster_spreadsheet')

    # ### end Alembic commands ###
