"""Add email valid column to Users table

Revision ID: c99c323b34f5
Revises: 6ee3ba2d87cc
Create Date: 2023-03-29 23:48:12.045908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99c323b34f5'
down_revision = '6ee3ba2d87cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_valid', sa.Boolean(), nullable=False,
                                      server_default='true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.drop_column('email_valid')

    # ### end Alembic commands ###
